# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('claim', '0002_auto_20160823_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.Department'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
