# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_auto_20160824_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='claim',
            name='state',
            field=models.BooleanField(choices=[(0, b'Intiated'), (1, b'Approved'), (2, b'Rejected')], default=0),
        ),
    ]
