# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claim', '0005_auto_20160825_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='claim',
            name='processed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
