# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0006_auto_20160825_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='title',
        ),
        migrations.AddField(
            model_name='claim',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='claim',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='claim',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
