# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 12:53
from __future__ import unicode_literals

import claim.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0007_auto_20160827_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='image',
            field=models.FileField(upload_to=b'claim_documents', validators=[claim.validators.validate_file_extension]),
        ),
    ]
