# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0008_auto_20160827_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='amount_approved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claim',
            name='requested_amount',
            field=models.IntegerField(default=0),
        ),
    ]
