# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0009_auto_20160903_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='requested_amount',
            new_name='amount_requested',
        ),
    ]
