# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 14:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_auto_20160827_1218'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(default=None, max_length=50)),
                ('visa', models.CharField(default=None, max_length=50)),
                ('flight_from', models.CharField(default=None, max_length=50)),
                ('flight_to', models.CharField(default=None, max_length=50)),
                ('travel_date', models.DateTimeField(default=datetime.datetime.now)),
                ('accomodation_at', models.CharField(default=None, max_length=50)),
                ('insurance_required', models.BooleanField(default=False)),
                ('laptop_config', models.CharField(default=None, max_length=100)),
                ('laptop_short_term', models.BooleanField(default=False)),
                ('laptop_long_term', models.BooleanField(default=False)),
                ('forex_details', models.CharField(default=None, max_length=100)),
                ('state', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.Department')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_processed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
