# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20160904_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
